Repository ES2-UFPI/MiAuDocao, pull requests merged in 2021-06, with the labels that each got.

#41 Configuração para Integração Contínua e Entrega Contínua
  .github/workflows/flutter_dev_pull_request.yml
  .github/workflows/flutter_main.yml
  .github/workflows/node_deploy_dev.yml
  .github/workflows/node_dev_pull_request.yml
  .github/workflows/node_main.yml
  miaudocao_api/__tests__/animal.test.js
  miaudocao_api/package-lock.json
  miaudocao_api/package.json
  miaudocao_app/analysis_options.yaml
  miaudocao_app/lib/widgets/animal_form.dart
  miaudocao_app/test/widget_test.dart
Labels: adjustment

#43 Atividade #29 concluída - Implementar endpoint para cadastro de usuário
  miaudocao_api/src/app.js
  miaudocao_api/src/controllers/usuarioController.js
  miaudocao_api/src/routes/usuarioRoute.js
Labels: backend, feature

#42 Atividade #28 concluída - Criar entidade usuário para se relacionar com a entidade animal
  .github/workflows/node_dev_pull_request.yml
  .github/workflows/node_main.yml
  db.sql
  miaudocao_api/__tests__/animal.test.js
  miaudocao_api/package-lock.json
  miaudocao_api/src/controllers/animalController.js
  miaudocao_api/src/utils/dbTestUtils.js
  miaudocao_app/lib/utils/configs.dart
  miaudocao_app/lib/utils/places_service.dart
  miaudocao_app/lib/views/busca_screen.dart
  miaudocao_app/lib/views/cadastrar_animal_screen.dart
  miaudocao_app/lib/views/explorar_screen.dart
  miaudocao_app/lib/views/visualizar_animal_screen.dart
Labels: backend, enhancement, frontend

#45 Atividade #33 concluída - Implementar endpoint para retornar dados de um usuário
  miaudocao_api/__tests__/animal.test.js
  miaudocao_api/src/controllers/usuarioController.js
Labels: backend, feature

#46 Atividade #26 concluída - Implementar manifestação de interesse
  db.sql
  miaudocao_api/src/app.js
  miaudocao_api/src/controllers/manifestarInteresseController.js
  miaudocao_api/src/routes/manifestarInteresseRoute.js
Labels: backend, feature

#47 Atividade #35 concluída - Implementar endpoint para retornar animais de um usuário
  miaudocao_api/src/controllers/usuarioController.js
  miaudocao_api/src/routes/usuarioRoute.js
Labels: backend, feature

#48 Atividade #36 concluída - Implementar endpoint para retornar interessados em um animal
  miaudocao_api/src/controllers/animalController.js
  miaudocao_api/src/routes/animalRoute.js
Labels: backend, feature

#49 Atividade #35 concluída - Implementar endpoint para retornar animais que o usuário tem interesse
  miaudocao_api/src/controllers/usuarioController.js
  miaudocao_api/src/routes/usuarioRoute.js
Labels: backend, feature

#50 Atividade #38 concluída - Implementar tela de histórico de animais
  miaudocao_app/lib/main.dart
  miaudocao_app/lib/utils/app_routes.dart
  miaudocao_app/lib/views/cadastrar_animal_screen.dart
  miaudocao_app/lib/views/espaco_usuario_screen.dart
  miaudocao_app/lib/views/interessados_screen.dart
  miaudocao_app/lib/views/tabs_screen.dart
  miaudocao_app/lib/views/welcome_login_screen.dart
  miaudocao_app/lib/widgets/animal_item.dart
Labels: feature, frontend

#51 Atividade #27 concluída - Implementar visualização do feed
  miaudocao_app/lib/views/busca_screen.dart
  miaudocao_app/lib/views/tabs_screen.dart
Labels: feature, frontend

#53 Atividade #26 concluída - Implementar manifestação de interesse
  miaudocao_api/__tests__/animal.test.js
  miaudocao_api/src/controllers/animalController.js
  miaudocao_app/lib/main.dart
  miaudocao_app/lib/models/animal.dart
  miaudocao_app/lib/views/busca_screen.dart
  miaudocao_app/lib/views/espaco_usuario_screen.dart
  miaudocao_app/lib/views/explorar_screen.dart
  miaudocao_app/lib/views/tabs_screen.dart
  miaudocao_app/lib/views/visualizar_animal_screen.dart
  miaudocao_app/lib/widgets/animal_item.dart
  miaudocao_app/pubspec.lock
Labels: backend, feature, frontend

#54 Atividade #34 concluída - Implementar tela de visualizar perfil de usuário
  miaudocao_app/lib/main.dart
  miaudocao_app/lib/utils/app_routes.dart
  miaudocao_app/lib/views/interessados_screen.dart
  miaudocao_app/lib/views/perfil_usuario_screen.dart
Labels: feature, frontend

#55 Atividade #31 concluída - Implementar endpoint para marcar animal como adotado
  db.sql
  miaudocao_api/src/controllers/animalController.js
  miaudocao_api/src/routes/animalRoute.js
  miaudocao_app/lib/models/animal.dart
  miaudocao_app/lib/views/busca_screen.dart
  miaudocao_app/lib/views/espaco_usuario_screen.dart
  miaudocao_app/lib/widgets/animal_item.dart
  miaudocao_app/lib/widgets/centralized_tip_text.dart
  miaudocao_app/pubspec.lock
Labels: backend, feature, frontend

#57 Atividade #56 concluída - Correções e testes
  .github/workflows/node_dev_pull_request.yml
  .github/workflows/node_main.yml
  miaudocao_api/__tests__/animal.test.js
  miaudocao_api/__tests__/usuario.test.js
  miaudocao_api/package.json
  miaudocao_api/src/controllers/animalController.js
  miaudocao_api/src/controllers/buscaController.js
  miaudocao_api/src/controllers/usuarioController.js
  miaudocao_app/lib/main.dart
  miaudocao_app/lib/views/busca_screen.dart
  miaudocao_app/lib/views/espaco_usuario_screen.dart
  miaudocao_app/lib/widgets/animal_form.dart
  miaudocao_app/lib/widgets/user_form.dart
Labels: backend, bug, frontend
