Repository ES2-UFPI/MiAuDocao, pull requests merged in 2021-05, with the labels that each got.

#3 Adjustment/configuração #2
  miaudocao_api/.gitignore
  miaudocao_api/package-lock.json
  miaudocao_api/package.json
Labels: adjustment

#14 Atividade #5 concluída - Implementar tela de cadastro de animal
  miaudocao_app/android/app/src/debug/AndroidManifest.xml
  miaudocao_app/assets/images/cat_dog.png
  miaudocao_app/lib/main.dart
  miaudocao_app/lib/models/animal.dart
  miaudocao_app/lib/utils/app_routes.dart
  miaudocao_app/lib/utils/places_service.dart
  miaudocao_app/lib/views/cadastrar_animal_screen.dart
  miaudocao_app/lib/widgets/animal_form.dart
  miaudocao_app/lib/widgets/centralized_tip_text.dart
  miaudocao_app/lib/widgets/custom_dropdown_button.dart
  miaudocao_app/lib/widgets/custom_textfield.dart
  miaudocao_app/lib/widgets/input_button.dart
  miaudocao_app/lib/widgets/search_address_modal.dart
  miaudocao_app/pubspec.lock
  miaudocao_app/pubspec.yaml
Labels: feature, frontend

#13 Atividade #6 concluída - Implementar endpoint de cadastro de animal
  db.sql
  miaudocao_api/package-lock.json
  miaudocao_api/package.json
  miaudocao_api/src/app.js
  miaudocao_api/src/configs/db.js
  miaudocao_api/src/controllers/animalController.js
  miaudocao_api/src/routes/animalRoute.js
  miaudocao_api/src/routes/index.js
  miaudocao_api/src/server.js
  miaudocao_api/src/utils/images.js
Labels: backend, feature

#15 Atividade #12 concluída - Implementar endpoint de requisitar informações de um animal
  miaudocao_api/package-lock.json
  miaudocao_api/package.json
  miaudocao_api/src/app.js
  miaudocao_api/src/controllers/animalController.js
  miaudocao_api/src/routes/animalRoute.js
Labels: backend, feature

#16 Atividade #8 concluída - Implementar endpoint de busca de animais
  miaudocao_api/src/app.js
  miaudocao_api/src/controllers/buscaController.js
  miaudocao_api/src/routes/buscaRoute.js
Labels: backend, feature

#17 Atividade #11 concluída - Implementar tela de visualizar animal
  miaudocao_app/android/app/build.gradle
  miaudocao_app/android/app/src/main/AndroidManifest.xml
  miaudocao_app/lib/main.dart
  miaudocao_app/lib/models/animal.dart
  miaudocao_app/lib/utils/app_routes.dart
  miaudocao_app/lib/views/visualizar_animal_screen.dart
  miaudocao_app/lib/widgets/address_details_modal.dart
  miaudocao_app/lib/widgets/address_info_card.dart
  miaudocao_app/lib/widgets/animal_identification.dart
  miaudocao_app/lib/widgets/animal_info_card.dart
  miaudocao_app/lib/widgets/fullscreen_image.dart
  miaudocao_app/pubspec.lock
  miaudocao_app/pubspec.yaml
  miaudocao_app/web/index.html
Labels: feature, frontend

#18 Atividade #7 concluída - Implementar tela de busca por mapa
  miaudocao_app/android/app/src/main/AndroidManifest.xml
  miaudocao_app/assets/images/marker.png
  miaudocao_app/lib/main.dart
  miaudocao_app/lib/models/animal.dart
  miaudocao_app/lib/views/busca_screen.dart
  miaudocao_app/lib/views/espaco_usuario_screen.dart
  miaudocao_app/lib/views/explorar_screen.dart
  miaudocao_app/lib/views/tabs_screen.dart
  miaudocao_app/lib/widgets/search_filters_modal.dart
  miaudocao_app/pubspec.lock
  miaudocao_app/pubspec.yaml
Labels: feature, frontend

#19 Atividade #9 concluída - Implementar widget de item de animal
  miaudocao_app/lib/widgets/animal_item.dart
Labels: feature, frontend

#20 Atividade #10 concluída - Implementar tela de resultado de busca
  miaudocao_app/lib/views/busca_screen.dart
Labels: feature, frontend

#24 Atividade #22 concluída - Ajustes no app
  miaudocao_app/lib/main.dart
  miaudocao_app/lib/views/cadastrar_animal_screen.dart
  miaudocao_app/lib/views/tabs_screen.dart
  miaudocao_app/lib/views/visualizar_animal_screen.dart
  miaudocao_app/lib/widgets/animal_info_card.dart
  miaudocao_app/lib/widgets/fullscreen_image.dart
  miaudocao_app/pubspec.yaml
Labels: enhancement, frontend

#23 Atividade #21 concluída - Corrigir bug na API
  miaudocao_api/src/configs/db.js
  miaudocao_api/src/controllers/buscaController.js
Labels: backend, bug
