Repository ES2-UFPI/MiAuDocao, pull requests merged in 2021-07, with the labels that each got.

#76 Atividade #67 concluída - Criar entidade notificação para armazenar dados de uma notificação
  db.sql
Labels: backend, enhancement

#77 Atividade #69 concluída - Implementar endpoint para requisitar notificações de um usuário
  miaudocao_api/src/controllers/notificacaoController.js
  miaudocao_api/src/routes/usuarioRoute.js
Labels: backend, feature

#78 Atividade #68 concluída - Implementar funcionalidade para exibir notificações
  miaudocao_app/lib/main.dart
  miaudocao_app/lib/models/notificacao.dart
  miaudocao_app/lib/utils/app_routes.dart
  miaudocao_app/lib/views/espaco_usuario_screen.dart
  miaudocao_app/lib/views/notificacoes_screen.dart
Labels: feature, frontend

#80 Atividade #59 concluída - Criar entidade pergunta para armazenar dados de uma pergunta e resposta
  db.sql
Labels: backend, enhancement

#83 Atividade #79 concluída - Correções na funcionalidade de busca
  miaudocao_api/src/controllers/buscaController.js
  miaudocao_app/lib/views/busca_screen.dart
Labels: backend, bug, frontend

#84 Atividade #62 concluída - Alterar tela de visualizar animal para novo card de perguntas e resposta
  miaudocao_app/lib/models/pergunta.dart
  miaudocao_app/lib/views/visualizar_animal_screen.dart
  miaudocao_app/lib/widgets/questions_answers_card.dart
Labels: feature, frontend

#86 Atividade #63 concluída - Implementar tela de perguntas e respostas a partir de uma visualização de animal
  miaudocao_app/lib/main.dart
  miaudocao_app/lib/utils/app_routes.dart
  miaudocao_app/lib/views/perguntas_screen.dart
  miaudocao_app/lib/views/visualizar_animal_screen.dart
  miaudocao_app/lib/widgets/questions_answers_card.dart
Labels: feature, frontend

#89 Atividade #66 concluída - Implementar funcionalidade para notificar o usuário de alguma novidade
  miaudocao_api/src/controllers/animalController.js
  miaudocao_api/src/controllers/perguntaController.js
  miaudocao_app/lib/views/notificacoes_screen.dart
Labels: backend, feature, frontend

#90 Atividade #70 concluída - Criar entidade favorito para armazenar favoritos
  db.sql
Labels: backend, enhancement

#95 Atividade #75 concluída - Criar tela de visualizar favoritos
  miaudocao_api/src/controllers/favoritoController.js
  miaudocao_api/src/routes/favoritoRoute.js
  miaudocao_app/lib/main.dart
  miaudocao_app/lib/models/animal.dart
  miaudocao_app/lib/utils/app_routes.dart
  miaudocao_app/lib/views/espaco_usuario_screen.dart
  miaudocao_app/lib/views/favoritos_screen.dart
  miaudocao_app/lib/views/visualizar_animal_screen.dart
Labels: feature, frontend

#93 Atividade #73 concluída - Criar endpoint para requisitar os favoritos de um usuário
  miaudocao_api/src/controllers/favoritoController.js
  miaudocao_api/src/routes/favoritoRoute.js
Labels: backend, feature

#96 Correções e testes
  miaudocao_api/__tests__/animal.test.js
  miaudocao_api/__tests__/favorito.test.js
  miaudocao_api/package-lock.json
  miaudocao_app/lib/models/animal_facade.dart
  miaudocao_app/lib/models/notificacao_facade.dart
  miaudocao_app/lib/models/pergunta_facade.dart
  miaudocao_app/lib/models/usuario_facade.dart
  miaudocao_app/lib/views/busca_screen.dart
  miaudocao_app/lib/views/cadastrar_animal_screen.dart
  miaudocao_app/lib/views/cadastrar_usuario_screen.dart
  miaudocao_app/lib/views/espaco_usuario_screen.dart
  miaudocao_app/lib/views/explorar_screen.dart
  miaudocao_app/lib/views/interessados_screen.dart
  miaudocao_app/lib/views/notificacoes_screen.dart
  miaudocao_app/lib/views/perfil_usuario_screen.dart
  miaudocao_app/lib/views/perguntas_screen.dart
  miaudocao_app/lib/views/visualizar_animal_screen.dart
  miaudocao_app/lib/views/welcome_login_screen.dart
Labels: backend, frontend
